# Default values for vllm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

deploymentStrategy:
  type: RollingUpdate

image:
  registry: registry.redhat.io
  repository: rhaii/vllm-cuda-rhel9
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.5.1"

imagePullSecrets: []

configuration:
  env: {}
  modelReference: ibm-granite/granite-3.3-2b-instruct  # not necessary if you're using an image
  extraArgs:
    - --disable-access-log-for-endpoints=/health,/metrics,/ping
  shm:
    size: 2Gi
  hfModelDownload:
    enabled: true
    huggingfaceToken: null
  cache:
    type: emptyDir # type can be one of pvc or emptyDir
    size: 20Gi
    emptyDir: {}
    pvc:
      accessModes:
        - ReadWriteOnce
  modelStorage:
    type: image  # type can be one of pvc, image, or emptyDir
    size: 20Gi
    mountPath: /tmp/hf_home
    emptyDir: {}
    pvc:
      accessModes:
        - ReadWriteOnce
    image:
      type: modelCar # type can be one of artifact or modelCar
      reference: "quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-2b-instruct"
      pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8000"

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  # KServe rhaii/vllm-cuda-rhel9 pods use readOnlyRootFilesystem: false so plugins can load
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8000

route:
  enabled: false
  annotations: {}
  tls:
    enabled: true
    insecureEdgeTerminationPolicy: Redirect
  subdomain: ""

resources:
  limits:
    cpu: 4
    memory: 16Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 2
    memory: 8Gi
    nvidia.com/gpu: 1

livenessProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 2
  periodSeconds: 60
  timeoutSeconds: 3
readinessProbe:
  httpGet:
    path: /v1/models
    port: http
  failureThreshold: 3
  periodSeconds: 30
  timeoutSeconds: 3
startupProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 180
  periodSeconds: 10
  timeoutSeconds: 3

nodeSelector: {}

tolerations:
  - key: nvidia.com/gpu
    effect: NoSchedule
    operator: Exists

affinity: {}
