---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  HF_HOME: {{ quote .Values.configuration.model.mountPath }}
  {{- if and (ne .Values.configuration.model.type "image") .Values.configuration.model.hfModelDownload.enabled }}
  HF_HUB_OFFLINE: "0"
  {{- else }}
  HF_HUB_OFFLINE: "1"
  {{- end }}
  {{- range $k, $v := .Values.configuration.env }}
  {{- if and (ne $k "HF_HOME") (ne $k "HF_HUB_OFFLINE") }}
  {{ $k }}: {{ quote $v }}
  {{- end }}
  {{- end }}
