{{- if eq .Values.configuration.model.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-storage
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  {{- with .Values.configuration.model.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.configuration.model.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.configuration.model.pvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.configuration.model.pvc.size }}
{{- end }}
{{- if eq .Values.configuration.cache.type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-cache
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  {{- with .Values.configuration.cache.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.configuration.cache.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.configuration.cache.pvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.configuration.cache.pvc.size }}
{{- end }}
