{{- if and (ne .Values.configuration.model.type "image") .Values.configuration.model.hfModelDownload.enabled }}
{{- $token := required "You need to provide a token in .configuration.model.hfModelDownload.huggingfaceToken if .configuration.model.hfModelDownload.enabled is set to true" .Values.configuration.model.hfModelDownload.huggingfaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ $token | quote }}
{{- end }}
